name: Generate Snake

on:
  schedule:
    # Run automatically every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
      - master

concurrency:
  group: generate-snake
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 1
          filter: blob:none
          sparse-checkout: |
            .github
          sparse-checkout-cone-mode: true

      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@d8f6715049803e982ee5ff501b6b9b7d5deeb09b # v3.5.0
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=#0052ff&color_dots=#ebedf0,#a5c2f9,#7aa2f7,#2b63d9,#003fa3
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#00d4ff&color_dots=#161b22,#003fa3,#0052ff,#00a8ff,#00d4ff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@5859b4ea7efe6b470a5b19c570460eae9323aefc # v3.2.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
